#!/bin/bash

#### Check for yay ####
ISYAY=/sbin/yay
if [ -f "$ISYAY" ]; then
    echo -e "yay was located, moving on.\n"
    yay -Suy
else
    echo -e "yay was not located, please install yay. Exiting script.\n"
    exit
fi

### Install packages for myself ####
read -n1 -rep 'Would you like to install the packages? (y,n)' INST
if [[ $INST == "Y" || $INST == "y" ]]; then
    yay -S --noconfirm oxwm-git thunar ttf-jetbrains-mono-nerd noto-fonts-emoji \
    pamixer pactl starship brightnessctl bluez bluez-utils \
    bluetui obsidian xpdf TLP tlpui firefox \
    alacritty rofi xclip feh picom kmix fish vlc vlc-plugin-ffmpeg \
    vlc-plugin-libav vlc-plugin-gstreamer gnome-disk kitty wine winetricks \
    pulseaudio-bluetooth
    
    # Start the bluetooth service
    echo -e "Starting the Bluetooth Service and TLP service...\n"
    sudo systemctl enable --now bluetooth.service
    sudo systemctl enable --now tlp.service
    sleep 2

    # # echo -e "Starting Power Profiles Daemon...\n"
    # # sudo systemctl enable power-profiles-daemon.service
    # sleep 2
fi

### Copy Config Files ###
read -n1 -rep 'Would you like to copy config files? (y,n)' CFG
if [[ $CFG == "Y" || $CFG == "y" ]]; then
    echo -e "Copying config files...\n"
    mkdir ~/.config
    mkdir ~/.scripts
    mkdir ~/Desktop
    mkdir ~/Documents
    mkdir ~/Videos
    mkdir ~/Photos
    
    cp -R /.config/ ~/.config/
    cp -R /.scripts/ ~/.scripts/
    cp .bashrc ~/
    cp .xinitrc ~/

    sudo chmod +x ~/.scripts/WTTR/wttr
    sudo chmod +x ~/.scripts/BTC-Price/WatchList
fi


### Script is done ###
echo -e "Script had completed.\n"
echo -e "Set up User.js after firefire fox launch if wanted"
